version: '3.0'

services:

  spring_app:
    container_name: spring_app
    image: abousalim/spring_app
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://spring_db:5432/student
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    depends_on:
      - spring_db

  spring_db:
    container_name: spring_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: student
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}